# Project configuration
spring:
  application:
    name: j_delivery



  # DB configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/j_delivery
    username: jack
    password: 9376570167
    driver-class-name: org.postgresql.Driver
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        jdbc:
          batch_size: 10
        order_updates: true
        order_inserts: true
        format_sql: true
        generate_statistics: true
        default_schema: postgres



  # Flyway configuration
  flyway:
    baseline-on-migrate: true
    enabled: true
    validate-on-migrate: true
    baseline-version: 0
    schemas: postgres



  # Redis configuration
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password:
      lettuce:
        pool:
          max-active: ${REDIS_POOL_LETTUCE_MAX_ACTIVE:32}
          max-idle: ${REDIS_POOL_LETTUCE_MAX_IDLE:16}
          min-idle: ${REDIS_POOL_LETTUCE_MIN_IDLE:8}
          max-wait: ${REDIS_POOL_LETTUCE_MAX_WAIT:2000}
      database: 0
      timeout: ${REDIS_CONNECT_TIMEOUT:2000}
      default-ttl: ${REDIS_DEFAULT_TTL:30000}
      order-ttl: ${REDIS_ORDER_TTL:5000}
      merchant-ttl: ${REDIS_MERCHANT_TTL:5000}



# Tomcat configuration (milliseconds)
server:
  port: ${SERVER_PORT:8081}
  tomcat:
    accept-count: ${TOMCAT_ACCEPT_COUNT:100}
    max-connections: ${TOMCAT_MAX_CONNECTIONS:1000}
    threads:
      max: ${TOMCAT_MAX_THREADS:200}
      min-spare: ${TOMCAT_MIN_SPARE_THREADS:20}
  compression:
    enabled: true
    min-response-size: 2KB
    mime-types: application/json, application/xml, text/xml, text/plain



# Kafka
kafka:
  bootstrapServers: ${KAFKA_BOOTSTRAP_SERVERS}
  groupId: ${KAFKA_CARD_GROUP_ID}
  clientId: ${KAFKA_CARD_CLIENT_ID}
  acksConfig: ${KAFKA_ACKS_CONFIG}
  retriesConfig: ${KAFKA_RETRIES_CONFIG:3}
  lingerMsConfig: ${KAFKA_LINGER_MS_CONFIG:100}
  clientDnsLookup: ${KAFKA_CLIENT_DNS_LOOKUP}
  batchSizeConfig: ${KAFKA_BATCH_SIZE_CONFIG:16384}
  bufferMemoryConfig: ${KAFKA_BUFFER_MEMORY_CONFIG:32768}
  autoOffsetResetConfig: ${KAFKA_AUTO_OFFSET_RESET_CONFIG}